### ISSUE TITLE
Session issue

### ISSUE THREAD

**Issue by MostHated** [andersfylling/disgord#138] opened 2019-05-27 05:16 UTC
Hey there,
I am pretty new to Go (only been at it a few days) but have made a Python Discord bot before. I wanted to learn go so I figured converting my bot would be a good way to get my hands dirty. I had started using DiscordGo, but a number of things frustrated me, namely the fact that I spent 5 or so hours trying to wrap the stupid logger, but no matter which way I tried it would not be how I wanted it, so I wanted to give this bot a try. I have only been at it for an hour or two, but even in that short time I already prefer it. I did have a (hopefully) quick question though in regards to disgord.Session. 

I really liked the setup I had going with DiscordGo as I was using [this for injection](https://github.com/sarulabs/di), exrouter, as well as a slightly customized [version of this fella](https://github.com/shaned24/crabbot-discord). Most of it so far I have not had an issue converting over, but for some reason I seem to keep getting stuck when it comes to disgord.Session.

Here is an example of how I had my setup.

```Go
type Verifier struct {
	routeContext *routeContext
}

type routeContext struct {
	di       di.Container
	Settings *config.MainSettings
	Session  *disgord.Session      // --- Session -------------------------------------------------------------------------------------------------------------------------
	Routes   []cmdroutes.Route
}

func (v *Verifier) VerifierRun(di di.Container) {
	settings := di.Get("configData").(config.Data).MainSettings

	client:= disgord.New(&disgord.Config{
		BotToken: settings.System.Token,
		Logger:   disgord.DefaultLogger(false), // debug=false1
	})
	defer client.StayConnectedUntilInterrupted()

	context := &routeContext{Settings: &settings,
		Session: *disgord.Session,                     // --- This is where I would normally put session --------------------------------------------------------------------
		di:      di,
		Routes: []cmdroutes.Route{
			cmdroutes.NewSubRoute(di),
			cmdroutes.NewUser(di),
			cmdroutes.NewDirectMessage(),
			cmdroutes.NewAvatar(),
			cmdroutes.NewPing(),
			cmdroutes.NewListRoles(di)}}

	// create a handler and bind it to new message events
	client.On(disgord.EvtMessageCreate, func(session disgord.Session, evt *disgord.MessageCreate) { // --- Session ? ------------------------------------------------------
		msg := evt.Message
		if msg.Content == "ping" {
			_, _ = msg.Reply(session, "pong")
		}
	})
	}
}

// --- This I have not bothered messing with much aside from changing the exrouter to disgordrouter as per the creators available integration ---------------------------
func (rc *routeContext) registerRoutes(di di.Container, session *disgord.Session, Routes ...cmdroutes.Route) {
	router := disgordrouter.New()

	cmdroutes.RegisterRoutes(
		router,
		Routes...,
	)

	session.AddHandler(func(_ *disgord.Session, m *disgord.MessageCreate) {
		log.Printf("Message %v", m.Content)
		log.Printf("Message %v", m.Type)
		_ = router.FindAndExecute(*session, rc.Settings.System.CommandPrefix, *session.User.ID, m.Message)
	})
}

```

I keep getting an "Invalid indirect" issue or "missing argument for conversion".  As I mentioned, I am pretty new to Go so I am sure I am just missing understanding something, or I missed something. Do you happen to have any advice to perhaps point me in the right direction?

I definitely appreciate the hard work you put into making this and I look forward to using it!
Thanks,
-MH

**Comment by andersfylling** [comment] 2019-05-27 07:44
Hi, right off the bat I do notice one detail; You use disgord.Session as a pointer. However, since this is an interface you should use it as `disgord.Session` and not `*disgord.Session`. 

This might be a bit tricky to explain as python does not have interfaces (I think?). But an interface just means that this variable or parameter can only take a type that holds the methods defined in an interface.

Say I have interface A in function FUNC:
```go
type A interface {}

func FUNC(a A) {
  ...
}
```

Now I can only pass Go types that holds the methods defined in A. Since A does not actually have any methods, you can literally pass in anything (int, string, CustomType, etc.). If we add some methods to interface A:
```go
type A interface {
	Help() string
}
```
We can now only pass in types that has a `Help() string` method signature. Such as:
```go
type B int
func (b B) Help() string {
	return strconv.Itoa(b)
}
```


To be fair, you might already understand interfaces and this was just redundant :laughing: . But change this:
```go
context := &routeContext{Settings: &settings,
		Session: *disgord.Session,             // --- This is where I would normally put session 
```

To this:
```go
context := &routeContext{Settings: &settings,
		Session: disgord.Session,             // --- This is where I would normally put session 
```

Does that fix the issue for you?

**Comment by MostHated** [comment] 2019-05-27 18:47
I appreciate the reply. Unfortunately it still gives me an error when I try it with or without the pointer. I did notice that it went away though if I changed it to the following:

```Go
	context := &routeContext{
		DI:       di,
		Client:   disgord.Client{},
		Settings: &settings,
		Session:  disgord.Session(client), // ----------
		Routes: []cmdroutes.Route{
			cmdroutes.NewSubRoute(di),
			cmdroutes.NewUser(di),
			cmdroutes.NewDirectMessage(),
			cmdroutes.NewAvatar(),
			cmdroutes.NewPing(),
			cmdroutes.NewListRoles(di)},
		BotID: 1,
	}
```


So my overall now looks like this:

```Go
package verifier

import (
	log "github.com/sirupsen/logrus"

	"github.com/Necroforger/dgrouter/disgordrouter"
	"github.com/instance-id/GoVerifier/verify/cmdroutes"

	"github.com/andersfylling/disgord"
	"github.com/instance-id/GoVerifier/verify/config"
	"github.com/sarulabs/di"
)

type Verifier struct {
	routeContext *routeContext
}

type routeContext struct {
	DI       di.Container
	Client   disgord.Client
	Settings *config.MainSettings
	Session  disgord.Session
	Routes   []cmdroutes.Route
	BotID    disgord.Snowflake
}

func (rc *routeContext) registerRoutes(di di.Container, session disgord.Session, Routes ...cmdroutes.Route) {
	router := disgordrouter.New()
	cmdroutes.RegisterRoutes(
		router,
		Routes...,
	)

	session.On(disgord.EvtMessageCreate, func(session disgord.Session, evt *disgord.MessageCreate) {
		log.Printf("Message %v", evt.Message.Content)
		log.Printf("Message %v", evt.Message.Type)
		_ = router.FindAndExecute(session, rc.Settings.System.CommandPrefix, rc.BotID, evt.Message)
	})
}

func (v *Verifier) VerifierRun(di di.Container) (*routeContext, error) {
	settings := di.Get("configData").(config.Data).MainSettings

	client := disgord.New(&disgord.Config{
		BotToken: settings.System.Token,
		Logger:   disgord.DefaultLogger(false), // debug=false1
	})
	user, err := client.GetCurrentUser()
	if err != nil {
		return nil, err
	}

	context := &routeContext{
		DI:       di,
		Client:   disgord.Client{},
		Settings: &settings,
		Session:  disgord.Session(client),
		Routes: []cmdroutes.Route{
			cmdroutes.NewSubRoute(di),
			cmdroutes.NewUser(di),
			cmdroutes.NewDirectMessage(),
			cmdroutes.NewAvatar(),
			cmdroutes.NewPing(),
			cmdroutes.NewListRoles(di)},
		BotID: user.ID,
	}

	// create a handler and bind it to new message events
	client.On(disgord.EvtMessageCreate, func(session disgord.Session, evt *disgord.MessageCreate) {
		msg := evt.Message
		if msg.Content == "ping" {
			_, _ = msg.Reply(session, "pong")
		}
	})
	return context, nil
}

func (v *Verifier) Start() error {
	err := v.routeContext.Client.Connect()
	if err != nil {
		return err
	}
	return nil
}

func (v *Verifier) Close() error {
	return v.routeContext.Session.Disconnect()
}

```

I have not tested anything yet, as there are a few more things associated with the route handler that I need to change, I just got too tired as I had been up for 2 days, lol. Currently though, there are no errors. Unfortunately that doesn't exactly mean that things are going to work properly, but it's a start, lol.

**Comment by andersfylling** [comment] 2019-05-27 18:56
Nice to hear. I've never tried that library of yours before. But if it does work out as intended, please leave a comment on that before you close the issue. Would be great to know about it :)

**Comment by MostHated** [comment] 2019-05-28 18:08
There was a slight issue with dgrouter's disgordrouter adapter for disgord as there were some changes on your end (SendMsgString -> SendMsg, CreateChannelMessage -> CreateMessage, ChannelEmbed -> Embed) but I got them changed and submitted a PR for it and all seems to be working well now. Do you happen to keep a running changelog somewhere or anything similar somewhere to keep track of breaking changes when you push updates? I looked around but didn't see one. It would definitely be helpful to possibly know when, or even just before an update comes out so that things can be updated elsewhere.

Thanks,
-MH

**Comment by andersfylling** [comment] 2019-05-28 18:21
Yes. These can be found in /docs at https://github.com/andersfylling/disgord/tree/develop/docs with the prefix CHANGELOG- and then the release number.

Do note that officially DisGord does not support projects that do not use go modules as these issues can then easily occur. Especially now that DisGord is still under development. Hopefully, such cases won't happen when v1 is released.

Great to hear you got it working!

**Closed by andersfylling** 2019-05-28 18:21 UTC
Labels: question

**Comment by MostHated** [comment] 2019-05-28 18:29
Oh! I went to look back to see if the router was using modules after you just mentioned that didn't realize it was you who had actually made that suggestion. So then you already knew what was going on, lol. My bad. I am still getting used to the PR functionality of Github (and the web interfaces for it).
