### ISSUE TITLE
Empty VoiceStates even with ignore cache flag on GetGuild function

### ISSUE THREAD

**Issue by saanuregh** [andersfylling/disgord#311] opened 2020-06-26 14:11 UTC
**Describe the bug**
Guild.VoiceStates is empty on calling GetGuild() with and without ignore the cache message.

**Expected behavior**
VoiceStates should be non-empty for the guild if there is member in voice channel.

**Error messages**
No error messages.

**Desktop (please complete the following information):**
 - Golang version: v1.13.12
 - Using Go modules? yes
 - Disgord version? v0.18.0
 - Connected to the gateway before using REST methods? yes

**Additional context**
I modified the source Guild struct and removed the omitempty tag, and it worked.

**Comment by andersfylling** [comment] 2020-06-29 07:47
I'm currently moving out of my apartment, but ill look into this when I get the chance. A PR might be faster.

**Comment by MagnusFrater** [comment] 2020-07-01 06:00
@saanuregh can you make a PR with your changes?

**Comment by andersfylling** [comment] 2020-07-01 18:40
so I looked at it and the issue is that caching for voice states isn't really a thing in Disgord, yet.

When you call GetGuild you get the complete response from Discord and whatever is in the cache. However, discord does not send voice states on a GetGuild request as stated in their documentation here: <https://discord.com/developers/docs/resources/guild#guild-object>

So this issue boils down to: missing caching functionality for voice states.

**Comment by andersfylling** [comment] 2020-07-01 18:52
Related: https://github.com/andersfylling/disgord/issues/288 https://github.com/andersfylling/disgord/issues/127

**Comment by saanuregh** [comment] 2020-07-01 23:18
That's what I did for my bot, I just used the voicestateevent to cache it in memory.
for reference https://github.com/saanuregh/bowot

**Comment by andersfylling** [comment] 2020-08-20 21:22
alright, so with the new cache. please feel free to add support for voice states. it should be fairly straight forward now =)

**Comment by andersfylling** [comment] 2020-10-24 19:36
I'm going to close this as it's "dead".

**Closed by andersfylling** 2020-10-24 19:36 UTC
Labels: bug

**Comment by golubkovden** [comment] 2021-02-09 11:40
any updates? 

Still getting empty VoiceStates in guild.

**Comment by andersfylling** [comment] 2021-02-09 18:52
It seems that PR for voice state caching never came in.
Regardless, I think that the REST requests should be cleaned up a little, and be more similar to the discord api docs.

Instead, when voice state caching becomes a thing, a new "REST" method can be created to fetch voice states for a guild. Which would also reduce GC.
